---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gol-db-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels: gol-db-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      name: gol-db-pod
      labels:
        name: gol-db-deploy
    spec:
      containers:
        - name: gol-db-deploy
          image: peddiraju3122b/gol:1.1
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gol-db-vol
              mountPath: /gol
      volumes:
        - name: gol-db-vol
          secret:
            secretName: gol