---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spc-svc 
  annotations:
    imageregistry: https://hub.docker.com/layers/peddiraju3122b/spc/1.1    
spec:
  rules:
    - http: 
        paths:
          - path: peddiraju3122b/spc/1.1
            backend:
              service:
                name: spc-svc
                port: 
                  number: 8080
            pathType: Exact
