---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spc-db-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels: spc-db-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      name: spc-db-pod
      labels:
        name: spc-db-deploy
    spec:
      containers:
        - name: spc-db-deploy
          image: peddiraju3122b/spc:1.1
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: spc-db-vol
              mountPath: /spc
      volumes:
        - name: spc-db-vol
          secret:
            secretName: spc