---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachedb-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      name: cachedb-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: cachedb-pod
      labels:
        name: cachedb-deploy        
    spec:
      containers:
        - name: cachedb
          image: library/redis:5.0-alpine
          ports:
            - containerPort: 6379
              protocol : TCP