---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleorcore-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      name: saleorcore-deploy
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: saleorcore-pod
      labels:
        name: saleorcore-deploy
    spec:
      containers:
        - name: saleorcore
          ports:
            - containerPort: 8000 
              protocol : TCP
          
            